alter table CO_DEPENDENT
  add CONSTRAINT `fk_DEPENDENT_EMPLOYEE1`
   FOREIGN KEY (`ESSN`)
   REFERENCES `CO_EMPLOYEE` (`SSN`)
    ON DELETE CASCADE
   ON UPDATE NO ACTION;
alter table CO_WORKS_ON
  add CONSTRAINT `fk_EMPLOYEE_has_PROJECT_EMPLOYEE1`
    FOREIGN KEY (`ESSN`)
    REFERENCES `CO_EMPLOYEE` (`SSN`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table CO_WORKS_ON
  add CONSTRAINT `fk_EMPLOYEE_has_PROJECT_PROJECT1`
    FOREIGN KEY (`PNumber`)
    REFERENCES `CO_PROJECT` (`PNumber`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table CO_DEPT_LOCATION  
 add CONSTRAINT `fk_DEPT_LOCATION_DEPARTMENT1`
    FOREIGN KEY (`DNumber`)
    REFERENCES `CO_DEPARTMENT` (`DNumber`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table CO_EMPLOYEE  
  add CONSTRAINT `fk_EMPLOYEE_DEPARTMENT`
   FOREIGN KEY (`DNumber`)
    REFERENCES `CO_DEPARTMENT` (`DNumber`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table CO_EMPLOYEE   
  add CONSTRAINT `fk_EMPLOYEE_EMPLOYEE1`
    FOREIGN KEY (`SupervisorSSN`)
    REFERENCES `CO_EMPLOYEE` (`SSN`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table CO_DEPARTMENT 
  add CONSTRAINT `fk_DEPARTMENT_EMPLOYEE1`
   FOREIGN KEY (`MgrSSN`)
    REFERENCES `CO_EMPLOYEE` (`SSN`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
alter table CO_PROJECT
  add CONSTRAINT `fk_PROJECT_DEPARTMENT1`
   FOREIGN KEY (`DNumber`)
    REFERENCES `CO_DEPARTMENT` (`DNumber`)
	ON DELETE CASCADE
    ON UPDATE NO ACTION;
